import { createContext, useContext, type ReactNode } from "react";
import type { BackupLoadMode, BackupLoadShape } from "../../dispatch/backup";
import type { CandidateMetrics, RankContext, RankingMode } from "../../dispatch/rank";
import type { DispatchStrategy, SimulationResult } from "../../dispatch/types";
import type { CustomerGroup } from "../../sun-daddy/customers";
import type { ProjectListItem } from "../../sun-daddy/types";
import type { RankSuccess, SweepFailure } from "./model";
import type { WizardStepId } from "./wizard";

export type StudyMeta = {
  customerName: string;
  projectName: string;
  utility: string | null;
};

export type SizerContextValue = {
  step: WizardStepId;
  maxReached: WizardStepId;
  canNext: boolean;
  hasData: boolean;
  goNext: () => void;
  goBack: () => void;
  goTo: (step: WizardStepId) => void;
  query: string;
  setQuery: (value: string) => void;
  busy: boolean;
  sunMessage: string | null;
  sunError: boolean;
  loadedNote: string | null;
  /** Why step 1 cannot advance after a Sun Daddy project load. */
  missingLoadMessage: string | null;
  /** Measured vs estimated, when the study names load.hourly_source. */
  loadSourceBadge: string | null;
  groups: CustomerGroup[];
  openCustomerKey: string | null;
  setOpenCustomerKey: (key: string | null) => void;
  searchProjects: () => void;
  openProject: (project: ProjectListItem) => void;
  loadExample: () => void;
  source: "none" | "example" | "manual" | "sun";
  manualOpen: boolean;
  setManualOpen: (open: boolean) => void;
  loadText: string;
  setLoadText: (value: string) => void;
  solarText: string;
  setSolarText: (value: string) => void;
  readLoadText: () => void;
  readSolarText: () => void;
  readLoadFile: (text: string) => void;
  readSolarFile: (text: string) => void;
  inputWarnings: string[];
  meta: StudyMeta;
  rateName: string;
  annualLoadKwh: number;
  peakKw: number;
  annualSolarKwh: number;
  tariffWarnings: string[];
  checkWarnings: string[];
  billedText: string;
  setBilledText: (value: string) => void;
  simpleRate: boolean;
  setSimpleRate: (value: boolean) => void;
  flatEnergy: string;
  setFlatEnergy: (value: string) => void;
  peakEnergy: string;
  setPeakEnergy: (value: string) => void;
  peakStart: string;
  setPeakStart: (value: string) => void;
  peakEnd: string;
  setPeakEnd: (value: string) => void;
  facilities: string;
  setFacilities: (value: string) => void;
  peakDemand: string;
  setPeakDemand: (value: string) => void;
  fixedCharge: string;
  setFixedCharge: (value: string) => void;
  exportCredit: string;
  setExportCredit: (value: string) => void;
  modeId: string;
  setModeId: (value: string) => void;
  peakTarget: string;
  setPeakTarget: (value: string) => void;
  backupHours: string;
  setBackupHours: (value: string) => void;
  catalogNotice: string;
  catalogSource: string;
  catalogPlaceholder: string | null;
  catalogBusy: boolean;
  reloadCatalog: () => void;
  projectIds: readonly string[];
  strategy: DispatchStrategy;
  setStrategy: (value: DispatchStrategy) => void;
  rte: string;
  setRte: (value: string) => void;
  degradation: string;
  setDegradation: (value: string) => void;
  socMin: string;
  setSocMin: (value: string) => void;
  socMax: string;
  setSocMax: (value: string) => void;
  discount: string;
  setDiscount: (value: string) => void;
  escalator: string;
  setEscalator: (value: string) => void;
  analysisYears: string;
  setAnalysisYears: (value: string) => void;
  maxQuantity: string;
  setMaxQuantity: (value: string) => void;
  backupMode: BackupLoadMode;
  setBackupMode: (value: BackupLoadMode) => void;
  backupShape: BackupLoadShape;
  setBackupShape: (value: BackupLoadShape) => void;
  backupPercent: string;
  setBackupPercent: (value: string) => void;
  criticalKw: string;
  setCriticalKw: (value: string) => void;
  outageSoc: string;
  setOutageSoc: (value: string) => void;
  outageSolar: boolean;
  setOutageSolar: (value: boolean) => void;
  model: RankSuccess | SweepFailure;
  selection: { top: CandidateMetrics; selected: CandidateMetrics; pinned: boolean } | null;
  detail: SimulationResult | null;
  chartSeries: { name: string; points: { kwh: number; savings: number }[] }[];
  unmetPeak: boolean;
  unmetBackup: boolean;
  chooseBattery: (batteryId: string) => void;
  chooseQuantity: (quantity: number) => void;
  selectStack: (batteryId: string, quantity: number) => void;
  resetOverride: () => void;
  buildingPeakKw: number;
  rankContext: RankContext;
  rankMode: RankingMode | null;
};

const SizerContext = createContext<SizerContextValue | null>(null);

export function SizerProvider({ value, children }: { value: SizerContextValue; children: ReactNode }) {
  return <SizerContext.Provider value={value}>{children}</SizerContext.Provider>;
}

export function useSizer(): SizerContextValue {
  const value = useContext(SizerContext);
  if (!value) throw new Error("Sizer controls are only available inside the sizer.");
  return value;
}
